-- Seed the cases table. Idempotent (uses INSERT OR REPLACE).
-- Apply with: wrangler d1 execute cs2-prices --file=seed-cases.sql

INSERT OR REPLACE INTO cases (id, name, released, pool, rare_type, has_gloves, notable) VALUES
  ('fracture',                  'Fracture Case',                  '2020-08-06', 'active',       'Knife',  0, 'AK Legion of Anubis'),
  ('dreams_nightmares',         'Dreams & Nightmares Case',       '2022-01-20', 'active',       'Knife',  0, 'Community designed, AK Nightwish'),
  ('recoil',                    'Recoil Case',                    '2022-07-01', 'active',       'Knife',  0, 'AK Ice Coaled, AWP Chromatic'),
  ('revolution',                'Revolution Case',                '2023-02-09', 'active',       'Knife',  0, 'AK Head Shot, M4A4 Temukau'),
  ('kilowatt',                  'Kilowatt Case',                  '2024-02-06', 'active',       'Knife',  0, 'First CS2 case, Kukri knife'),
  ('gallery',                   'Gallery Case',                   '2024-08-22', 'active',       'Knife',  0, 'AK Inheritance, AWP Chrome Cannon'),
  ('fever',                     'Fever Case',                     '2025-03-13', 'active',       'Knife',  0, 'M4A1-S Vaporwave'),
  ('snakebite',                 'Snakebite Case',                 '2021-05-03', 'rare',         'Gloves', 1, 'Glove case, M4A4 In Living Color'),
  ('clutch',                    'Clutch Case',                    '2018-02-15', 'rare',         'Gloves', 1, 'First glove case'),
  ('csgo_weapon',               'CS:GO Weapon Case',              '2013-08-14', 'discontinued', 'Knife',  0, 'FIRST CASE EVER. Holy grail.'),
  ('csgo_weapon_2',             'CS:GO Weapon Case 2',            '2013-11-08', 'discontinued', 'Knife',  0, 'Second case ever, extremely rare'),
  ('csgo_weapon_3',             'CS:GO Weapon Case 3',            '2014-02-12', 'discontinued', 'Knife',  0, 'Third case, only pistol skins'),
  ('esports_2013',              'eSports 2013 Case',              '2013-08-14', 'discontinued', 'Knife',  0, 'First esports case, AWP BOOM'),
  ('winter_offensive',          'Winter Offensive Weapon Case',   '2013-12-18', 'discontinued', 'Knife',  0, 'AWP Electric Hive'),
  ('operation_bravo',           'Operation Bravo Case',           '2013-09-19', 'discontinued', 'Knife',  0, 'First operation case, AK Fire Serpent'),
  ('operation_phoenix',         'Operation Phoenix Weapon Case',  '2014-02-20', 'discontinued', 'Knife',  0, 'AWP Asiimov debut'),
  ('huntsman',                  'Huntsman Weapon Case',           '2014-05-01', 'discontinued', 'Knife',  0, 'Huntsman knife introduced'),
  ('operation_breakout',        'Operation Breakout Weapon Case', '2014-07-01', 'discontinued', 'Knife',  0, 'Butterfly knife, M4A1-S Cyrex'),
  ('esports_2014_summer',       'eSports 2014 Summer Case',       '2014-07-10', 'discontinued', 'Knife',  0, 'AWP Corticera'),
  ('operation_vanguard',        'Operation Vanguard Weapon Case', '2014-11-11', 'discontinued', 'Knife',  0, 'AK Wasteland Rebel'),
  ('chroma',                    'Chroma Case',                    '2015-01-08', 'discontinued', 'Knife',  0, 'AWP Man-o-war, M4A4 Dragon King'),
  ('chroma_2',                  'Chroma 2 Case',                  '2015-04-15', 'discontinued', 'Knife',  0, 'M4A1-S Hyper Beast'),
  ('chroma_3',                  'Chroma 3 Case',                  '2016-04-27', 'discontinued', 'Knife',  0, 'M4A1-S Chantico''s Fire'),
  ('falchion',                  'Falchion Case',                  '2015-05-26', 'discontinued', 'Knife',  0, 'Falchion knife, AWP Hyper Beast'),
  ('shadow',                    'Shadow Case',                    '2015-09-17', 'discontinued', 'Knife',  0, 'Shadow daggers, USP-S Kill Confirmed'),
  ('revolver',                  'Revolver Case',                  '2015-12-08', 'discontinued', 'Knife',  0, 'AK Point Disarray'),
  ('operation_wildfire',        'Operation Wildfire Case',        '2016-02-17', 'discontinued', 'Knife',  0, 'Bowie knife, AK Fuel Injector'),
  ('gamma',                     'Gamma Case',                     '2016-06-15', 'discontinued', 'Knife',  0, 'AWP Phobos, M4A1-S Mecha'),
  ('gamma_2',                   'Gamma 2 Case',                   '2016-08-18', 'discontinued', 'Knife',  0, 'AK Neon Revolution'),
  ('glove',                     'Glove Case',                     '2016-11-28', 'discontinued', 'Gloves', 1, 'FIRST GLOVE CASE. Premium tier.'),
  ('spectrum',                  'Spectrum Case',                  '2017-03-15', 'discontinued', 'Knife',  0, 'AK Bloodsport, USP Neo-Noir'),
  ('operation_hydra',           'Operation Hydra Case',           '2017-05-23', 'discontinued', 'Gloves', 1, 'AWP Oni Taiji, glove case'),
  ('spectrum_2',                'Spectrum 2 Case',                '2017-09-14', 'discontinued', 'Knife',  0, 'AK The Empress'),
  ('cs20',                      'CS20 Case',                      '2019-10-18', 'discontinued', 'Knife',  0, 'Classic knife, FAMAS Commemoration'),
  ('danger_zone',               'Danger Zone Case',               '2018-12-06', 'discontinued', 'Knife',  0, 'AWP Neo-Noir, AK Asiimov'),
  ('horizon',                   'Horizon Case',                   '2018-07-31', 'discontinued', 'Knife',  0, 'Stiletto/Talon/Ursus/Navaja debut'),
  ('prisma',                    'Prisma Case',                    '2019-03-13', 'discontinued', 'Knife',  0, 'AWP Atheris, AK Uncharted'),
  ('prisma_2',                  'Prisma 2 Case',                  '2020-03-31', 'discontinued', 'Knife',  0, 'AK Phantom Disruptor'),
  ('shattered_web',             'Shattered Web Case',             '2019-11-18', 'discontinued', 'Knife',  0, 'Skeleton/Nomad/Survival knives'),
  ('operation_riptide',         'Operation Riptide Case',         '2021-09-22', 'discontinued', 'Knife',  0, 'AK Leet Museo, AWP Big Game'),
  ('operation_broken_fang',     'Operation Broken Fang Case',     '2020-12-03', 'discontinued', 'Gloves', 1, 'AK Slate, M4A1-S Printstream');
